-- AlterTable: add AUDIT fields to AnnualReview
ALTER TABLE "AnnualReview" ADD COLUMN IF NOT EXISTS "auditQ1"    INTEGER;
ALTER TABLE "AnnualReview" ADD COLUMN IF NOT EXISTS "auditQ2"    INTEGER;
ALTER TABLE "AnnualReview" ADD COLUMN IF NOT EXISTS "auditQ3"    INTEGER;
ALTER TABLE "AnnualReview" ADD COLUMN IF NOT EXISTS "auditQ4"    INTEGER;
ALTER TABLE "AnnualReview" ADD COLUMN IF NOT EXISTS "auditQ5"    INTEGER;
ALTER TABLE "AnnualReview" ADD COLUMN IF NOT EXISTS "auditQ6"    INTEGER;
ALTER TABLE "AnnualReview" ADD COLUMN IF NOT EXISTS "auditQ7"    INTEGER;
ALTER TABLE "AnnualReview" ADD COLUMN IF NOT EXISTS "auditQ8"    INTEGER;
ALTER TABLE "AnnualReview" ADD COLUMN IF NOT EXISTS "auditQ9"    INTEGER;
ALTER TABLE "AnnualReview" ADD COLUMN IF NOT EXISTS "auditQ10"   INTEGER;
ALTER TABLE "AnnualReview" ADD COLUMN IF NOT EXISTS "auditCScore" INTEGER;
ALTER TABLE "AnnualReview" ADD COLUMN IF NOT EXISTS "auditScore"  INTEGER;
